### ISSUE TITLE
ES 6.x

### ISSUE THREAD

**Issue by Beenhakker** [myarik/django-rest-elasticsearch#19]
Hi,

Just curious: when will there be support for ES 6.x? I have already based my latest application on it.

Kind regards,

Bas

**Comment by dmvass** [comment]
Hi @Beenhakker,

The **django-rest-elasticsearc**h used [elasticsearch-dsl-py](https://github.com/elastic/elasticsearch-dsl-py) for Elasticsearch aptitudes integration and this one is supporting 6.x version now. If you are needs in some custom query to Elasticsearch you could overload [ElasticSearchFilter.get_es_query](https://github.com/myarik/django-rest-elasticsearch/blob/master/rest_framework_elasticsearch/es_filters.py#L180) for this.

**Comment by codekiln** [comment]
@kandziu will you please update [setup.py](https://github.com/myarik/django-rest-elasticsearch/blob/master/setup.py#L36) to allow for ES 6.x? 

Also, since `es_inspector` uses `rest_framework.schemas.AutoSchema` which [requires `djangorestframework>=3.7.0`](http://www.django-rest-framework.org/topics/3.7-announcement/), which has a number of breaking changes, this package should likely also list those constraints.

Also, I just happened to notice that setup.py has a different license than the one in the LICENSE file.

**Comment by dmvass** [comment]
@codekiln _setup.py_ fixed in the #23 and _djangorestframework>=3.7_ was closed in the #22
